name: cinemotion
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  animate_do: ^4.2.0
  animated_text_kit: ^4.3.0
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.4
  intl: ^0.20.2
  riverpod_annotation: ^3.0.0
  riverpod_generator: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env

fonts:
  - family: Product-Sans
    fonts:
      - asset: fonts/Product-Sans-Regular.ttf
      - asset: fonts/Product-Sans-Bold.ttf
        weight: 700
